services:
  pubsub:
    image: redis:trixie
    restart: "unless-stopped"
    ports:
      - "6379:6379"
    volumes:
      - redis-pubsub:/data

  insight:
    image: redis/redisinsight
    restart: "unless-stopped"
    ports:
      - "5540:5540"
    volumes:
      - redisInsight:/data


volumes:
  redis-pubsub:
  redisInsight:
